In [1]:
# import the necessary libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pmdarima
import datetime as dt

from pmdarima import auto_arima
from statsmodels.tsa.arima.model import ARIMA
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error

In [2]:
df = pd.read_csv('../datasets/cleaned_orders.csv')
print(df.dtypes)
df.head(2)

customer_id                               int64
order_date                               object
order_time                               object
item_id                                  object
item_quantity                             int64
item_price                              float64
item_discount_raw                       float64
item_discount_percentage                float64
item_disc_bins_item_disc_null             int64
item_disc_bins_item_disc_sub_twenty       int64
item_disc_bins_item_disc_sub_forty        int64
item_disc_bins_item_disc_sub_sixty        int64
item_disc_bins_item_disc_sub_eighty       int64
item_disc_bins_item_disc_sub_hundred      int64
dtype: object

,customer_id,order_date,order_time,item_id,item_quantity,item_price,item_discount_raw,item_discount_percentage,item_disc_bins_item_disc_null,item_disc_bins_item_disc_sub_twenty,item_disc_bins_item_disc_sub_forty,item_disc_bins_item_disc_sub_sixty,item_disc_bins_item_disc_sub_eighty,item_disc_bins_item_disc_sub_hundred
0,0,2022-04-29,18:29:49,Arzuaga blanco,1,49.0,0.0,0.0,1,0,0,0,0,0
1,0,2022-04-29,18:29:49,Arzuaga reserva,1,94.0,0.0,0.0,1,0,0,0,0,0